# Generated by Django 5.2.4 on 2025-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
